/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet,Linking, Text, View,  Alert,
} from 'react-native';
import iZooto from '../src';


export default class App extends React.Component {
  

 

    componentDidMount() {
      

      if (Platform.OS === 'ios') {
        iZooto.initiOSAppID("623638eaa956234fdb6b3f0f1990bd049a14312e");
        
        iZooto.addEventListener('register', (token) => {
          console.log("iZootoDevice Token", token)
      })
      iZooto.addEventListener('deepLinkData',(notification)=>
      {
        console.log("Notification Data",notification);
      })
      iZooto.addEventListener('landingURL',(notification)=>{
        console.log("Notification WebViewData",notification);

      })
      iZooto.addEventListener('receivePayload',(notification)=>
      {
        console.log("Notification Payload",notification);
      })

      iZooto.addUserProperty();
      
      
      
      }
      else
      {
        iZooto.initialize();
        iZooto.setDefaultTemplate(1)
        Linking.addEventListener(iZooto.onNotificationOpenedListener)
      iZooto.onNotificationOpenedListener(data =>{
        console.log("DeepLink Data Received",data);
      });      
      iZooto.onNotificationReceivedListener(payload => {
        console.log("Notification Payload",payload); 
      });
  
      iZooto.onWebViewListener(landingUrl =>{
        console.log("Landing URL",landingUrl); 
      });
      iZooto.onTokenReceivedListener(token =>{
        console.log("Token Received",token);
      });
        
      }
      //iZooto.initialize();
     // iZooto.initializeiOS();
     // Linking.addEventListener(iZooto.onNotificationOpenedListener)
      // iZooto.onNotificationOpenedListener(data =>{
      //   console.log("DeepLink Data Received",data);
      // });
  
      // iZooto.onNotificationReceivedListener(payload => {
      //   console.log("Notification Payload",payload); 
      // });
  
      // iZooto.onWebViewListener(landingUrl =>{
      //   console.log("Landing URL",landingUrl); 
      // });
      // iZooto.onTokenReceivedListener(token =>{
      //   console.log("Token Received",token);
      // });
      
   }
   componentWillUnmount()
   {
     iZooto.removeEventListener('deepLinkData')
   }
    
    
    
   
    render() {
        return (
            <View>
               
                <Text> React Native Library for iZooto  
                   Push Notifications Service </Text>

            </View>
        );
    }
}
